version: '3.8'

services:
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRESS_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:






# version: '3.8'

# services:
#   frontend:
#     image: "bethiane/frontend"
#     mem_limit: 128m
#     hostname: backend
#   backend:
#     image: "bethiane/backend"
#     mem_limit: 128m
#     hostname: backend
#   nginx:
#     image: "bethiane/nginx"
#     mem_limit: 128m
#     hostname: nginx
#     ports:
#       - "80:80"